add_newline = true

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$time\
$status\
$shell\
$character
"""

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
